### PR TITLE
changes after committed to main repository

### PR DESCRIPTION
**Pull request by Neodelf**
according to the [pull-request](https://github.com/bbatsov/ruby-style-guide/pull/551/files )

### CODE REVIEW

**Comment by arbox** [comment]
Very good point. It's good that you changed the base version. But please do not incorporate changes from upstream into this repository, it's solely my task. I do it on the regular basis once a week, and it makes my task much more complicated if I have to selectively incorporate changes.

The workflow is simple:
- if you think that all guides benefit from your changes please propose it to Bozhidar;
- I pull all the changes from the upstream and mark them as FIXME;
- I fix what I can and to my best knowledge;
- you  can work on all unfixed changes and on my errors and inconsistencies.

Thank you for your help.

**Comment by arbox** [comment]
I will reuse this chunk as soon as I incorporated the changes.

**Comment by Neodelf** [comment]
Of course, I`m so sorry about this changes from base version.
Thanks

**Comment by arbox** [comment]
Not at all, you are welcome. I'm happy if anybody wants to collaborate regularily. We simply need a workflow which makes things easier and not vice versa.

**Comment by arbox** [comment]
@Neodelf your changes are now incorporated along with other upstream changes. Thank you for your work :+1:

**Comment by Neodelf** [comment]
Awesome! Thank you too

**Pull request closed without merging**
